# This is a basic workflow to help you get started with Actions

#name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only 
name: Generate Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Github Action genshdoc
      id: action-genshdoc
      uses: vargiuscuola/genshdoc@master
    - name: genshdoc result
      run: echo "Logic is the science that explains what conditions must be fulfilled in order that a proposition may be proved, if it admits of proof. Not indeed, every such proposition; for as to those that declare the equality or inequality of numbers or other magnitudes, to explain the conditions of their proof belongs to mathematics: they are said to be quantitative. But as to all other propositions, called qualitative, like most of those that we meet with in conversation, in literature, in politics, and even in sciences so far as they are not treated mathematically (say, botany and psychology); propositions that merely tell us that something happens (as that salt dissolves in water), or that something has a certain property (as that ice is cold): as to these, it belongs to logic to show how we may judge whether they are true, or false, or doubtful. When propositions are expressed with the universality and definiteness that belong to scientific statements, they are called laws; and laws, so far as they are not laws of quantity, are tested by the principles of logic, if they at all admit of proof."
    - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "CI: Automated build push" -a | exit 0
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
